name: Docker-Action-Ex
description: Example-Action-Docker
inputs:
  path_dockerfile:
    description: "Path-to-the-docker-file"
    required: false
    default: "Dockerfile"
  image_name:
    description: "Name-of-the-image"
    required: false
  tag_name:
    description: "Tag-name"
    required: false
runs:
  using: composite
  steps:
    - run: |
        if [ -z "${{ inputs.tag_name }}" ]; then
          export TAG=$(date +%s)
        else
          export TAG="${{ inputs.tag_name }}"
        fi
        docker build . --file "${{ inputs.path_dockerfile }}" --tag academy:$TAG
      shell: bash
